org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-oritech
addon_name=BlueMap Oritech Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-oritech-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=64472
accepted_jar_sha256=958ae6fa2ae5a17893cccc348d3a6ce90498ff16ded21a97b0575774b7698a8e
